import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
// import { Button } from "@mantine/core";
import { Avatar, Text, Button, Paper } from "@mantine/core";
import UserStore from "../store/usersStore";
import { observer } from "mobx-react-lite";

interface UserInfoActionProps {
  avatar: string;
}

const inter = Inter({ subsets: ["latin"] });

function Home({ avatar }: UserInfoActionProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <Button>Settings</Button>
        </div>
        <span>
          {UserStore.tweets.map((item, id) => {
            return (
              <Paper
                key={id}
                radius="md"
                withBorder
                p="lg"
                sx={(theme) => ({
                  backgroundColor:
                    theme.colorScheme === "dark"
                      ? theme.colors.dark[8]
                      : theme.white,
                })}
              >
                <Avatar src={avatar} size={120} radius={120} mx="auto" />
                <Text ta="center" fz="lg" weight={500} mt="md">
                  {item.id}
                </Text>
                <Text ta="center" c="dimmed" fz="sm">
                  {item.title}
                </Text>

                <Button variant="default" fullWidth mt="md">
                  You
                </Button>
              </Paper>
            );
          })}
        </span>
      </main>
    </>
  );
}

export default observer(Home);
